name: Dependencies

on:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Update dependencies
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "deps: update dependencies 📦"
          title: "deps: update dependencies 📦"
          body: |
            🤖 This PR updates project dependencies to their latest versions.

            This is an automated PR created by the weekly dependency update workflow.

            ## Changes
            - Updates dependencies to their latest compatible versions
            - Maintains existing version constraints
            - Includes all necessary lockfile updates

            ## Validation
            - [ ] All tests pass
            - [ ] Build succeeds
            - [ ] No breaking changes introduced

            Please review the changes and merge if everything looks good!
          branch: deps/update-dependencies
          base: main
          labels: dependencies
